version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  main-ms:
    image: azold6/trabalho-final-backend-main:v1
    ports:
      - '8080:8080'
    environment:
      HOST: rabbitmq
    depends_on:
      - rabbitmq

  email-ms:
    image: azold6/trabalho-final-backend-email-ms:v1
    ports:
      - '8081:8080'
    environment:
      HOST: rabbitmq
    depends_on:
      - rabbitmq
      - main-ms

  frontend:
    image: azold6/trabalho-final-frontend:v1
    ports:
      - '4173:4173'